CREATE TABLE INVEJ.PLANIRANJE_MAPIRANJE
(
    VRSTA    VARCHAR2(100) NOT NULL,
    RED_BROJ NUMBER        NOT NULL,
    VREDNOST VARCHAR2(50)  NOT NULL
)
ORGANIZATION HEAP
TABLESPACE DES2
NOLOGGING
PCTFREE 10
PCTUSED 40
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
/
ALTER TABLE INVEJ.PLANIRANJE_MAPIRANJE
    ADD CONSTRAINT PLANIRANJE_MAPIRANJE_PK
    PRIMARY KEY (VRSTA,RED_BROJ,VREDNOST)
    USING INDEX TABLESPACE DES2
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
/
