CREATE TABLE INVEJ.PLANIRANJE_VIEW_POM
(
    SESSION_ID                    VARCHAR2(255) NOT NULL,
    PLAN_TIP_ID                   NUMBER        NOT NULL,
    PLAN_TIP_NAZIV                VARCHAR2(255)     NULL,
    PLAN_CIKLUS_ID                NUMBER        NOT NULL,
    PLAN_CIKLUS_NAZIV             VARCHAR2(255)     NULL,
    PLAN_CIKLUS_GODINA            NUMBER(4,0)       NULL,
    PLAN_PERIOD_ID                NUMBER        NOT NULL,
    PLAN_PERIOD_NAZIV             VARCHAR2(255)     NULL,
    PLAN_TRAJANJE_ID              NUMBER        NOT NULL,
    PLAN_TRAJANJE_DATUM_OD        DATE              NULL,
    PLAN_TRAJANJE_DATUM_DO        DATE              NULL,
    BROJ_DOK                      NUMBER        NOT NULL,
    VARIJANTA_ID                  NUMBER        NOT NULL,
    STAVKA_ID                     NUMBER        NOT NULL,
    ORG_DEO_ID                    NUMBER            NULL,
    ORG_DEO_NAZIV                 VARCHAR2(40)      NULL,
    BROJ_DOK1                     NUMBER            NULL,
    STATUS_PLAN                   NUMBER(2,0)       NULL,
    STATUS_VARIJANTA              NUMBER(2,0)       NULL,
    STATUS_STAVKA                 NUMBER(2,0)       NULL,
    OPIS_PLAN                     VARCHAR2(255)     NULL,
    OPIS_VARIJANTA                VARCHAR2(255)     NULL,
    GOTOV_PR_SIFRA                VARCHAR2(7)   NOT NULL,
    GOTOV_PR_NAZIV                VARCHAR2(30)      NULL,
    GOTOV_PR_JM                   VARCHAR2(3)       NULL,
    GOTOV_PR_SAST_SARZA           NUMBER            NULL,
    GOTOV_PR_PLAN_UMNOZAK_SARZE   NUMBER            NULL,
    GOTOV_PR_PLAN_ZELJENA_KOL     NUMBER            NULL,
    GOTOV_PR_SASTAVNICA           VARCHAR2(9)   NOT NULL,
    MATERIJAL_TIP                 VARCHAR2(2)   NOT NULL,
    MATERIJAL_STAVKA              NUMBER        NOT NULL,
    MATERIJAL_SIFRA               VARCHAR2(7)   NOT NULL,
    MATERIJAL_NAZIV               VARCHAR2(30)      NULL,
    MATERIJAL_SAS_SARZA           NUMBER            NULL,
    MATERIJAL_UMNOZAK_SARZE       NUMBER            NULL,
    MATERIJAL_PLAN_POTREBNA_KOL   NUMBER            NULL,
    MATERIJAL_JED_MERE            VARCHAR2(3)       NULL,
    JM_NABAVNA                    VARCHAR2(3)       NULL,
    FAKTOR_NABAVNE                NUMBER(11,5)      NULL,
    MATERIJAL_ZADNJA_NABAVNA_CENA NUMBER            NULL,
    GOTOV_PR_POSGR                NUMBER            NULL,
    MATERIJAL_POSGR               NUMBER            NULL
)
ORGANIZATION HEAP
TABLESPACE DES2
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
/
ALTER TABLE INVEJ.PLANIRANJE_VIEW_POM
    ADD CONSTRAINT PLANIRANJE_VIEW_POM_PK
    PRIMARY KEY (SESSION_ID,PLAN_TIP_ID,PLAN_CIKLUS_ID,PLAN_PERIOD_ID,PLAN_TRAJANJE_ID,BROJ_DOK,VARIJANTA_ID,STAVKA_ID,GOTOV_PR_SIFRA,GOTOV_PR_SASTAVNICA,MATERIJAL_TIP,MATERIJAL_STAVKA,MATERIJAL_SIFRA)
    USING INDEX TABLESPACE DES2
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
/
GRANT ALTER ON INVEJ.PLANIRANJE_VIEW_POM TO FULL_ACCESS
/
GRANT DEBUG ON INVEJ.PLANIRANJE_VIEW_POM TO FULL_ACCESS
/
GRANT DELETE ON INVEJ.PLANIRANJE_VIEW_POM TO FULL_ACCESS
/
GRANT FLASHBACK ON INVEJ.PLANIRANJE_VIEW_POM TO FULL_ACCESS
/
GRANT INSERT ON INVEJ.PLANIRANJE_VIEW_POM TO FULL_ACCESS
/
GRANT ON COMMIT REFRESH ON INVEJ.PLANIRANJE_VIEW_POM TO FULL_ACCESS
/
GRANT QUERY REWRITE ON INVEJ.PLANIRANJE_VIEW_POM TO FULL_ACCESS
/
GRANT SELECT ON INVEJ.PLANIRANJE_VIEW_POM TO FULL_ACCESS
/
GRANT UPDATE ON INVEJ.PLANIRANJE_VIEW_POM TO FULL_ACCESS
/
GRANT SELECT ON INVEJ.PLANIRANJE_VIEW_POM TO RESTRICT_ACCESS
/

Create public synonym PLANIRANJE_VIEW_POM FOR INVEJ.PLANIRANJE_VIEW_POM ;
