CREATE TABLE MONUS.ZALIHE_GOD_MAG_DATUMI
(
    ORG_DEO      NUMBER      NOT NULL,
    GODINA       NUMBER(4,0) NOT NULL,
    PROIZVOD     VARCHAR2(7) NOT NULL,
    MAX_DAT_PS   DATE            NULL,
    MIN_DAT_DOK  DATE            NULL,
    MAX_DAT_DOK  DATE            NULL,
    STANJE_PO_PS DATE            NULL,
    DAT_PS_1998  DATE            NULL,
    DAT_PS_1999  DATE            NULL,
    DAT_PS_2000  DATE            NULL,
    DAT_PS_2001  DATE            NULL,
    DAT_PS_2002  DATE            NULL,
    DAT_PS_2003  DATE            NULL,
    DAT_PS_2004  DATE            NULL,
    DAT_PS_2005  DATE            NULL,
    DAT_PS_2006  DATE            NULL,
    DAT_PS_2007  DATE            NULL,
    DAT_PS_2008  DATE            NULL,
    DAT_PS_2009  DATE            NULL,
    DAT_PS_2010  DATE            NULL
)
ORGANIZATION HEAP
TABLESPACE DES2
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
/
ALTER TABLE MONUS.ZALIHE_GOD_MAG_DATUMI
    ADD CONSTRAINT ZALIHE_GOD_MAG_DATUMI_PK
    PRIMARY KEY (ORG_DEO,GODINA,PROIZVOD)
    USING INDEX TABLESPACE DES2
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE(BUFFER_POOL DEFAULT)
    LOGGING
    ENABLE
    VALIDATE
/
