Select * 
From OS_PRIMOPREDAJA_STAVKA , OS_PRIMOPREDAJA
Where OS_PRIMOPREDAJA.POSLOVNA_GODINA        = 2006 and
      OS_PRIMOPREDAJA.BROJ                   = 115  and
      OS_PRIMOPREDAJA_STAVKA.POSLOVNA_GODINA = OS_PRIMOPREDAJA.POSLOVNA_GODINA AND
      OS_PRIMOPREDAJA_STAVKA.BROJ            = OS_PRIMOPREDAJA.BROJ and
