SELECT   OS.rowid , OS.*
/*
       OS_DOKUMENT.VRSTA, OS_DOKUMENT.TIP , OS_DOKUMENT.DOKUMENT  ,
       OS_DOKUMENT_STAVKA.STAVKA, OS_DOKUMENT_STAVKA.IDENT, OS_DOKUMENT_STAVKA.JM,
       OS_DOKUMENT_STAVKA.KOLICINA , OS_DOKUMENT_STAVKA.PROMENA_NV, OS_DOKUMENT_STAVKA.PROMENA_IV,
       OS_DOKUMENT_STAVKA.NABAVNA_VREDNOST, OS_DOKUMENT_STAVKA.OTPISANA_VREDNOST,
       OS_DOKUMENT_STAVKA.SADASNJA_VREDNOST, OS_DOKUMENT_STAVKA.VREDNOST, OS_DOKUMENT_STAVKA.VREDNOST_U_VALUTI,
       OS_DOKUMENT_STAVKA.OSTATAK_VREDN, OS_DOKUMENT_STAVKA.PROM_OSTATAK_VREDN, OS_DOKUMENT_STAVKA.REV_REZERVE
*/

From Os_Dokument_stavka os
Where --OS.Godina = 2000                      And
        OS.TIP = 701
--      OS.Dokument IN ( 68  )                      And
--      OS.ident > 315 and
